<a href="https://colab.research.google.com/github/patrickkirbyjr/DataPat/blob/main/convert_to_uppercase.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# How to Convert Column Names and Values to Uppercase in Pandas (Python Colab Tutorial)

# StRiNgS -> STRINGS

.rename()

.upper()

In [ ]:
# import libraries
import pandas as pd
import seaborn as sns

In [ ]:
# import dataset (built-in seaborn dataset)
penguins = sns.load_dataset('penguins')

In [ ]:
# rename columns (make them wacky)
wacky_cols = ['Species', 'iSLAND', 'Bill_Length_MM', 'BILL_DEPTH_MM', 'Flipper_Length_mm', 'body_mass_G', 'SEX']
penguins.columns = wacky_cols
penguins.head()

,Species,iSLAND,Bill_Length_MM,BILL_DEPTH_MM,Flipper_Length_mm,body_mass_G,SEX
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female

## Convert a Single Column Name to Uppercase

In [ ]:
# convert species column name to uppercase
penguins = penguins.rename(columns={
    'Species': 'SPECIES'
})
penguins.head()

,SPECIES,iSLAND,Bill_Length_MM,BILL_DEPTH_MM,Flipper_Length_mm,body_mass_G,SEX
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female

## Convert All Column Names to Uppercase

In [ ]:
# convert column names to uppercase
penguins.columns = penguins.columns.str.upper()
penguins.head()

,SPECIES,ISLAND,BILL_LENGTH_MM,BILL_DEPTH_MM,FLIPPER_LENGTH_MM,BODY_MASS_G,SEX
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female

## Convert an Entire Column to Uppercase

In [ ]:
# convert species column data to uppercase
penguins['SPECIES'] = penguins['SPECIES'].str.upper()
penguins.head()

,SPECIES,ISLAND,BILL_LENGTH_MM,BILL_DEPTH_MM,FLIPPER_LENGTH_MM,BODY_MASS_G,SEX
0,ADELIE,Torgersen,39.1,18.7,181.0,3750.0,Male
1,ADELIE,Torgersen,39.5,17.4,186.0,3800.0,Female
2,ADELIE,Torgersen,40.3,18.0,195.0,3250.0,Female
3,ADELIE,Torgersen,NaN,NaN,NaN,NaN,NaN
4,ADELIE,Torgersen,36.7,19.3,193.0,3450.0,Female

## Convert All Data to Uppercase

In [ ]:
# convert all data to uppercase
penguins = penguins.map(lambda x: x.upper() if isinstance(x, str) else x)
penguins.head()

,SPECIES,ISLAND,BILL_LENGTH_MM,BILL_DEPTH_MM,FLIPPER_LENGTH_MM,BODY_MASS_G,SEX
0,ADELIE,TORGERSEN,39.1,18.7,181.0,3750.0,MALE
1,ADELIE,TORGERSEN,39.5,17.4,186.0,3800.0,FEMALE
2,ADELIE,TORGERSEN,40.3,18.0,195.0,3250.0,FEMALE
3,ADELIE,TORGERSEN,NaN,NaN,NaN,NaN,NaN
4,ADELIE,TORGERSEN,36.7,19.3,193.0,3450.0,FEMALE

# PLEASE LIKE & SUBSCRIBE FOR MORE VIDEOS