<a href="https://colab.research.google.com/github/patrickkirbyjr/DataPat/blob/main/convert_to_lowercase.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# How to Convert Column Names and Values to Lowercase in Pandas (Python Colab Tutorial)

# StRiNgS -> strings

.rename()

.lower()

In [ ]:
# import libraries
import pandas as pd
import seaborn as sns

In [ ]:
# import dataset (built-in seaborn dataset)
penguins = sns.load_dataset('penguins')

In [ ]:
# rename columns (make them wacky)
wacky_cols = ['Species', 'iSLAND', 'Bill_Length_MM', 'BILL_DEPTH_MM', 'Flipper_Length_mm', 'body_mass_G', 'SEX']
penguins.columns = wacky_cols
penguins.head()

,Species,iSLAND,Bill_Length_MM,BILL_DEPTH_MM,Flipper_Length_mm,body_mass_G,SEX
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female

## Convert a Single Column Name to Lowercase

In [ ]:
# convert species column name to lowercase
penguins = penguins.rename(columns={
    'Species': 'species'
})
penguins.head()

,species,iSLAND,Bill_Length_MM,BILL_DEPTH_MM,Flipper_Length_mm,body_mass_G,SEX
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female

## Convert All Column Names to Lowercase

In [ ]:
# convert column names to lowercase
penguins.columns = penguins.columns.str.lower()
penguins.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female

## Convert an Entire Column to Lowercase

In [ ]:
# convert species column data to lowercase
penguins['species'] = penguins['species'].str.lower()
penguins.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,adelie,Torgersen,36.7,19.3,193.0,3450.0,Female

## Convert All Data to Lowercase

In [ ]:
# convert all data to lowercase (cannot use .lower)
penguins = penguins.map(lambda x: x.lower() if isinstance(x, str) else x)
penguins.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,adelie,torgersen,39.1,18.7,181.0,3750.0,male
1,adelie,torgersen,39.5,17.4,186.0,3800.0,female
2,adelie,torgersen,40.3,18.0,195.0,3250.0,female
3,adelie,torgersen,NaN,NaN,NaN,NaN,NaN
4,adelie,torgersen,36.7,19.3,193.0,3450.0,female

# PLEASE LIKE & SUBSCRIBE FOR MORE VIDEOS