<a href="https://colab.research.google.com/github/patrickkirbyjr/DataPat/blob/main/fill_missing_values.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# How to Fill Missing Values in Pandas (Python Colab Tutorial)

## Identify Missing Values

In [ ]:
# import libraries
import pandas as pd
import seaborn as sns

In [ ]:
# import dataset (built-in seaborn dataset)
penguins = sns.load_dataset('penguins')
penguins

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male

In [ ]:
# count missing values for each column
missing_counts = penguins.isna().sum()
print(missing_counts)

species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  11
dtype: int64

## Fill Missing Categorical Values with "Unknown"

In [ ]:
# replace missing categorical values
penguins['sex'] = penguins['sex'].fillna('Unknown')
penguins

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,Unknown
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,Unknown
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male

## Fill Missing Numerical Values with Median/Mean

In [ ]:
# calculate median and mean values
median_bill_length = penguins['bill_length_mm'].median()
median_bill_depth = penguins['bill_depth_mm'].median()
median_flipper_length = penguins['flipper_length_mm'].median()
average_body_mass = penguins['body_mass_g'].mean()


# replace missing values calculated values
penguins['bill_length_mm'] = penguins['bill_length_mm'].fillna(median_bill_length)
penguins['bill_depth_mm'] = penguins['bill_depth_mm'].fillna(median_bill_depth)
penguins['flipper_length_mm'] = penguins['flipper_length_mm'].fillna(median_flipper_length)
penguins['body_mass_g'] = penguins['body_mass_g'].fillna(average_body_mass)
penguins

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.10,18.7,181.0,3750.000000,Male
1,Adelie,Torgersen,39.50,17.4,186.0,3800.000000,Female
2,Adelie,Torgersen,40.30,18.0,195.0,3250.000000,Female
3,Adelie,Torgersen,44.45,17.3,197.0,4201.754386,Unknown
4,Adelie,Torgersen,36.70,19.3,193.0,3450.000000,Female
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,44.45,17.3,197.0,4201.754386,Unknown
340,Gentoo,Biscoe,46.80,14.3,215.0,4850.000000,Female
341,Gentoo,Biscoe,50.40,15.7,222.0,5750.000000,Male
342,Gentoo,Biscoe,45.20,14.8,212.0,5200.000000,Female
343,Gentoo,Biscoe,49.90,16.1,213.0,5400.000000,Male

## Yes, there is a better way! Get subscribed to see how in a future video.

# Final Check

In [ ]:
# count missing values for each column
missing_counts = penguins.isna().sum()
print(missing_counts)

species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          0
sex                  0
dtype: int64