<a href="https://colab.research.google.com/github/patrickkirbyjr/DataPat/blob/main/filter_with_between.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# How to Filter Ranges in Pandas Using .between()

❌ BAD:

penguins[(penguins['flipper_length_mm'] >= 190) & (penguins['flipper_length_mm'] <= 210)]

✅ GOOD:

penguins[penguins['flipper_length_mm'].between(190, 210)

⚙️ PARAMETERS:

1. Left boundary
2. Right boundary
3. Inclusivity - both (default), neither, left, right

In [ ]:
# import libraries
import pandas as pd
import seaborn as sns

In [ ]:
# import dataset (built-in seaborn dataset)
penguins = sns.load_dataset('penguins')
penguins

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male

In [ ]:
# get penguins with medium flipper lengths - default exclusivity (both)
medium_flipper_penguins = penguins[penguins['flipper_length_mm'].between(190,210)]
medium_flipper_penguins

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,Male
7,Adelie,Torgersen,39.2,19.6,195.0,4675.0,Male
8,Adelie,Torgersen,34.1,18.1,193.0,3475.0,NaN
...,...,...,...,...,...,...,...
296,Gentoo,Biscoe,47.5,14.2,209.0,4600.0,Female
318,Gentoo,Biscoe,48.4,14.4,203.0,4625.0,Female
326,Gentoo,Biscoe,41.7,14.7,210.0,4700.0,Female
328,Gentoo,Biscoe,43.3,14.0,208.0,4575.0,Female
329,Gentoo,Biscoe,48.1,15.1,209.0,5500.0,Male

In [ ]:
# get penguins with medium flipper lengths - inclusivity both
medium_flipper_penguins = penguins[penguins['flipper_length_mm'].between(190,210,'both')]
medium_flipper_penguins

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,Male
7,Adelie,Torgersen,39.2,19.6,195.0,4675.0,Male
8,Adelie,Torgersen,34.1,18.1,193.0,3475.0,NaN
...,...,...,...,...,...,...,...
296,Gentoo,Biscoe,47.5,14.2,209.0,4600.0,Female
318,Gentoo,Biscoe,48.4,14.4,203.0,4625.0,Female
326,Gentoo,Biscoe,41.7,14.7,210.0,4700.0,Female
328,Gentoo,Biscoe,43.3,14.0,208.0,4575.0,Female
329,Gentoo,Biscoe,48.1,15.1,209.0,5500.0,Male

In [ ]:
# get penguins with medium flipper lengths - inclusivity left
medium_flipper_penguins = penguins[penguins['flipper_length_mm'].between(195,210, 'left')]
medium_flipper_penguins

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
7,Adelie,Torgersen,39.2,19.6,195.0,4675.0,Male
14,Adelie,Torgersen,34.6,21.1,198.0,4400.0,Male
16,Adelie,Torgersen,38.7,19.0,195.0,3450.0,Female
17,Adelie,Torgersen,42.5,20.7,197.0,4500.0,Male
...,...,...,...,...,...,...,...
280,Gentoo,Biscoe,45.3,13.8,208.0,4200.0,Female
296,Gentoo,Biscoe,47.5,14.2,209.0,4600.0,Female
318,Gentoo,Biscoe,48.4,14.4,203.0,4625.0,Female
328,Gentoo,Biscoe,43.3,14.0,208.0,4575.0,Female
329,Gentoo,Biscoe,48.1,15.1,209.0,5500.0,Male

In [ ]:
# get penguins with medium flipper lengths - inclusivity right
medium_flipper_penguins = penguins[penguins['flipper_length_mm'].between(195,210,'right')]
medium_flipper_penguins

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
14,Adelie,Torgersen,34.6,21.1,198.0,4400.0,Male
17,Adelie,Torgersen,42.5,20.7,197.0,4500.0,Male
35,Adelie,Dream,39.2,21.1,196.0,4150.0,Male
43,Adelie,Dream,44.1,19.7,196.0,4400.0,Male
53,Adelie,Biscoe,42.0,19.5,200.0,4050.0,Male
...,...,...,...,...,...,...,...
296,Gentoo,Biscoe,47.5,14.2,209.0,4600.0,Female
318,Gentoo,Biscoe,48.4,14.4,203.0,4625.0,Female
326,Gentoo,Biscoe,41.7,14.7,210.0,4700.0,Female
328,Gentoo,Biscoe,43.3,14.0,208.0,4575.0,Female
329,Gentoo,Biscoe,48.1,15.1,209.0,5500.0,Male

In [ ]:
# get penguins with medium flipper lengths - inclusivity neither
medium_flipper_penguins = penguins[penguins['flipper_length_mm'].between(190,210, 'neither')]
medium_flipper_penguins

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
7,Adelie,Torgersen,39.2,19.6,195.0,4675.0,Male
8,Adelie,Torgersen,34.1,18.1,193.0,3475.0,NaN
13,Adelie,Torgersen,38.6,21.2,191.0,3800.0,Male
...,...,...,...,...,...,...,...
280,Gentoo,Biscoe,45.3,13.8,208.0,4200.0,Female
296,Gentoo,Biscoe,47.5,14.2,209.0,4600.0,Female
318,Gentoo,Biscoe,48.4,14.4,203.0,4625.0,Female
328,Gentoo,Biscoe,43.3,14.0,208.0,4575.0,Female
329,Gentoo,Biscoe,48.1,15.1,209.0,5500.0,Male

# Thanks for watching!

## If you want to learn more data science concepts, be sure to **like** and **subscribe**.