<a href="https://colab.research.google.com/github/patrickkirbyjr/DataPat/blob/main/rename_columns.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# How to Rename Columns in Pandas (Python Colab Tutorial)

## Renaming Columns

Important first step in making sense of data

Fix typos and make columns easier to work with

.rename() makes this easy!

In [ ]:
# import libraries
import pandas as pd
import seaborn as sns

In [ ]:
# import dataset (built-in seaborn dataset)
penguins = sns.load_dataset('penguins')
penguins.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female

## Renaming Specific Columns

In [ ]:
# rename specific columns using a dictionary
penguins_renamed = penguins.rename(columns={
    'species': 'penguin_species',
    'island': 'origin_island'
})
penguins_renamed.head()

,penguin_species,origin_island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female

## Renaming Every Column

In [ ]:
# create a list of new column names
new_columns = ['Species', 'Island', 'Bill_Length', 'Bill_Depth', 'Flipper_Length', 'Body_Mass', 'Sex']

# assign new names
penguins_renamed.columns = new_columns
penguins_renamed.head()

,Species,Island,Bill_Length,Bill_Depth,Flipper_Length,Body_Mass,Sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female

# PLEASE LIKE & SUBSCRIBE FOR MORE VIDEOS