<a href="https://colab.research.google.com/github/patrickkirbyjr/DataPat/blob/main/swap_with_replace.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# How to Replace Values in a Pandas DataFrame Using .replace()

## What is .replace()?

Used to replace values in a Pandas Series or DataFrame

Tell it what to find and give it something to replace it with

In [ ]:
# import libraries
import pandas as pd
import seaborn as sns

In [ ]:
# import dataset (built-in seaborn dataset)
penguins = sns.load_dataset('penguins')
penguins.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female

## Replacing Specific Values

In [ ]:
# print unique penguin species
print(penguins['species'].unique())

['Adelie' 'Chinstrap' 'Gentoo']

In [ ]:
# replace "Gentoo" species with "Northern Gentoo"
penguins['species'] = penguins['species'].replace('Gentoo', 'Northern Gentoo')
print(penguins['species'].unique())

['Adelie' 'Chinstrap' 'Northern Gentoo']

In [ ]:
# see changes in dataframe
penguins.tail()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
339,Northern Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Northern Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female
341,Northern Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male
342,Northern Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female
343,Northern Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male

## Replacing Multiple Values with the Same Value

In [ ]:
# replace island names with "Deception"
penguins['island'] = penguins['island'].replace(['Biscoe', 'Dream', 'Torgersen'], 'Deception')
print(penguins['island'].unique())

['Deception']

In [ ]:
# see changes in dataframe
penguins.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Deception,39.1,18.7,181.0,3750.0,Male
1,Adelie,Deception,39.5,17.4,186.0,3800.0,Female
2,Adelie,Deception,40.3,18.0,195.0,3250.0,Female
3,Adelie,Deception,NaN,NaN,NaN,NaN,NaN
4,Adelie,Deception,36.7,19.3,193.0,3450.0,Female

## Replacing Multiple Values with Different Values

In [ ]:
# create dictionary for sex abbreviations
sex_abb = {'Male': 'M', 'Female': 'F'}

# replace penguin sex values with abbreviations
penguins['sex'] = penguins['sex'].replace(sex_abb)
penguins.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Deception,39.1,18.7,181.0,3750.0,M
1,Adelie,Deception,39.5,17.4,186.0,3800.0,F
2,Adelie,Deception,40.3,18.0,195.0,3250.0,F
3,Adelie,Deception,NaN,NaN,NaN,NaN,NaN
4,Adelie,Deception,36.7,19.3,193.0,3450.0,F

### Note: If you want to replace NA values, it is best to use .fillna()

# Thanks for watching!

## If you want to learn more data science concepts, be sure to **like** and **subscribe**.